finance.finance_transfer_gateway.*:
  type: config_entity
  label: 'Transfer gateway config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: finance.finance_transfer_gateway.plugin.[%parent.plugin]
    uuid:
      type: string
